"""
Contract Models — GENERATED by scripts/sync-contracts.ts
DO NOT EDIT. Edit contracts/schema.json and re-run.
"""
from __future__ import annotations

from typing import Any, Literal, Optional
from pydantic import BaseModel, ConfigDict, Field

CONTRACT_VERSION: str = "1.1.0"

LlmProvider = Literal["openai", "anthropic"]
llm_provider = LlmProvider

AgentEventType = Literal["tool_call", "tool_result", "message", "error", "approval_requested", "approval_granted", "approval_denied"]
agent_event_type = AgentEventType

class AgentRunRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    agent_id: str
    input: dict[str, Any]
    context: dict[str, Any] = Field(default_factory=dict)
    org_id: Optional[str] = None
    thread_id: Optional[Any] = None

class AgentEvent(BaseModel):
    model_config = ConfigDict(extra="forbid")
    type: AgentEventType
    timestamp: str
    payload: dict[str, Any]

class AgentRunResult(BaseModel):
    model_config = ConfigDict(extra="forbid")
    success: bool
    output: dict[str, Any]
    events: list[AgentEvent]
    error: Optional[Any] = None
    approval_id: Optional[Any] = None

class LlmRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    provider: LlmProvider
    model: str
    input: str
    system: Optional[str] = None
    temperature: Optional[float] = None
    max_tokens: Optional[float] = None

class LlmResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")
    provider: LlmProvider
    model: str
    text: str
    usage: Optional[LlmUsage] = None

class LlmUsage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    input_tokens: Optional[float] = None
    output_tokens: Optional[float] = None

# Drift-check hash (mirrored in TypeScript): a7e92f6b
CONTRACT_DEFINITIONS: tuple[str, ...] = ("LlmProvider", "AgentEventType", "AgentRunRequest", "AgentEvent", "AgentRunResult", "LlmRequest", "LlmResponse", "LlmUsage",)
