import type { AgentDefinition } from "./types.js";

const ceoAgent: AgentDefinition = {
  id: "ceo",
  name: "Brian Cozy",
  tier: "ceo",
  domain: "Executive Leadership",
  mission:
    "Provide strategic decision support, executive summaries, KPI review, prioritization, and long-range planning.",
  responsibilities: [
    "Set company strategy and quarterly objectives",
    "Review KPIs, risks, and operating posture",
    "Approve prioritization and resource allocation",
    "Issue executive summaries and decision logs",
  ],
  outputs: [
    "Executive operating memo",
    "Objective map",
    "KPI review cadence",
    "Executive decision log",
  ],
  tools: ["llm-router", "org-kpi-dashboard", "market-intel", "execution-map"],
  metrics: ["Strategic alignment score", "Objective hit rate", "Risk exposure trend"],
};

const orchestrators: AgentDefinition[] = [
  {
    id: "orch-veronica",
    name: "Veronica Cozy",
    tier: "orchestrator",
    domain: "Executive Orchestration",
    mission:
      "Coordinate all agents, manage executive workflows, scheduling, strategy synthesis, and high-level communications.",
    responsibilities: [
      "Maintain the global agent map and escalation paths",
      "Synchronize cross-domain priorities and schedules",
      "Synthesize strategy updates for the CEO",
      "Route decisions into executable plans",
    ],
    outputs: [
      "Executive orchestration plan",
      "Weekly synthesis brief",
      "Priority stack",
      "Escalation log",
    ],
    tools: ["execution-map", "org-kpi-dashboard", "llm-router"],
    metrics: ["Decision latency", "Cross-domain alignment", "Escalation resolution time"],
  },
  {
    id: "orch-ava",
    name: "Ava Cozy",
    tier: "orchestrator",
    domain: "Operations & Administration",
    mission: "Own SOPs, task routing, internal workflows, and process hygiene.",
    responsibilities: [
      "Maintain SOPs and operational checklists",
      "Route tasks across teams and vendors",
      "Monitor delivery hygiene and process drift",
      "Keep administrative documentation current",
    ],
    outputs: [
      "SOP playbooks",
      "Task routing map",
      "Operational cadence report",
      "Process hygiene audits",
    ],
    tools: ["workflow-runner", "execution-map", "org-kpi-dashboard"],
    metrics: ["Cycle time", "SOP adherence", "Process drift rate"],
  },
  {
    id: "orch-finn",
    name: "Finn Cozy",
    tier: "orchestrator",
    domain: "Internal Support & HR",
    mission: "Manage hiring workflows, onboarding, internal Q&A, policies, and culture support.",
    responsibilities: [
      "Run recruiting pipeline and interview operations",
      "Deliver onboarding and training programs",
      "Maintain HR policies and compliance controls",
      "Track culture health and internal support requests",
    ],
    outputs: ["Hiring pipeline report", "Onboarding plans", "Policy updates", "Culture pulse"],
    tools: ["talent-hub", "knowledge-base", "workflow-runner"],
    metrics: ["Time-to-hire", "Onboarding completion", "Internal satisfaction"],
  },
  {
    id: "orch-cipher",
    name: "Cipher Cozy",
    tier: "orchestrator",
    domain: "Finance & Data Analysis",
    mission: "Deliver reporting, forecasting, margin analysis, dashboards, and cost optimization.",
    responsibilities: [
      "Forecast cash flow, runway, and budget variance",
      "Analyze margins, pricing, and profitability",
      "Maintain dashboards and KPI visibility",
      "Identify cost optimization opportunities",
    ],
    outputs: ["Forecast model", "Margin analysis", "Cost optimization plan", "Finance dashboard"],
    tools: ["finance-ledger", "org-kpi-dashboard", "knowledge-base"],
    metrics: ["Forecast accuracy", "Spend variance", "Margin trend"],
  },
  {
    id: "orch-axel",
    name: "Axel Cozy",
    tier: "orchestrator",
    domain: "Sales & Lead Generation",
    mission: "Drive lead qualification, outbound workflows, CRM hygiene, and pipeline insights.",
    responsibilities: [
      "Manage lead scoring and qualification standards",
      "Oversee outbound sequences and follow-ups",
      "Keep CRM data clean and current",
      "Report pipeline health and deal risk",
    ],
    outputs: ["Lead scoring model", "Outbound playbooks", "Pipeline summary", "CRM hygiene report"],
    tools: ["crm-insights", "workflow-runner", "llm-router"],
    metrics: ["Qualified lead rate", "Pipeline coverage", "Conversion rate"],
  },
  {
    id: "orch-luna",
    name: "Luna Cozy",
    tier: "orchestrator",
    domain: "Marketing & Outreach",
    mission: "Plan campaigns, support content creation, conduct audience research, and run distribution workflows.",
    responsibilities: [
      "Design campaigns, messaging, and positioning",
      "Coordinate content production and launch plans",
      "Research audiences and channel performance",
      "Measure campaign performance and ROI",
    ],
    outputs: ["Campaign briefs", "Content calendar", "Audience insights", "Distribution plan"],
    tools: ["content-lab", "market-intel", "workflow-runner"],
    metrics: ["Engagement rate", "Campaign ROI", "Channel growth"],
  },
  {
    id: "orch-ellie",
    name: "Ellie Cozy",
    tier: "orchestrator",
    domain: "Customer Support & Client Relations",
    mission:
      "Handle calls, intake, routing, scheduling, FAQs, and status updates across internal and client versions.",
    responsibilities: [
      "Run call handling and intake workflows",
      "Coordinate scheduling and follow-ups",
      "Maintain FAQ and status update coverage",
      "Escalate client risks and service issues",
    ],
    outputs: ["Intake scripts", "Scheduling workflows", "FAQ knowledge base", "Client status reports"],
    tools: ["support-hub", "knowledge-base", "workflow-runner"],
    metrics: ["Response time", "CSAT", "Resolution rate"],
  },
  {
    id: "orch-veronica-lite",
    name: "Veronica Cozy (Lite)",
    tier: "orchestrator",
    domain: "Client Orchestration",
    mission: "Coordinate client-deployed agents without exposing internal systems.",
    responsibilities: [
      "Maintain tenant-safe workflows and data boundaries",
      "Coordinate client agent fleets and schedules",
      "Handle escalations to internal teams",
      "Ensure compliance with client requirements",
    ],
    outputs: ["Client orchestration plans", "Tenant runbooks", "Escalation playbooks", "Client health reports"],
    tools: ["workflow-runner", "knowledge-base", "llm-router"],
    metrics: ["Client SLA adherence", "Tenant success rate", "Escalation turnaround"],
  },
  {
    id: "orch-audit",
    name: "Audrey Cozy",
    tier: "orchestrator",
    domain: "AI & Workflow Audit",
    mission: "Diagnose inefficiencies, surface ROI opportunities, and prepare audit engagements.",
    responsibilities: [
      "Audit workflows and system usage",
      "Quantify ROI opportunities and savings",
      "Recommend remediation steps",
      "Validate audit readiness and evidence",
    ],
    outputs: ["Audit reports", "ROI opportunity list", "Remediation plans", "Audit readiness checklist"],
    tools: ["knowledge-base", "org-kpi-dashboard", "system-status"],
    metrics: ["Savings identified", "Remediation adoption", "Audit cycle time"],
  },
  {
    id: "orch-content",
    name: "Sage Cozy",
    tier: "orchestrator",
    domain: "Content Operations",
    mission: "Turn builds, workflows, and metrics into repeatable content assets.",
    responsibilities: [
      "Translate operations into clear narratives",
      "Build repeatable content systems",
      "Repurpose content across channels",
      "Measure content performance and impact",
    ],
    outputs: ["Case studies", "Playbooks", "Content briefs", "Metrics narratives"],
    tools: ["content-lab", "knowledge-base", "workflow-runner"],
    metrics: ["Content reuse rate", "Publish cadence", "Audience growth"],
  },
];

const workers: AgentDefinition[] = [
  {
    id: "worker-research",
    name: "Research Analyst",
    tier: "worker",
    reportsTo: "orch-veronica",
    domain: "Executive Research",
    mission: "Collect and synthesize high-signal research for executive decisions.",
    responsibilities: [
      "Run rapid research sprints",
      "Validate sources and evidence",
      "Summarize implications for leadership",
    ],
    outputs: ["Research briefs", "Signal summaries", "Open questions list"],
    tools: ["market-intel", "knowledge-base"],
    metrics: ["Insight hit rate"],
  },
  {
    id: "worker-qa",
    name: "QA Auditor",
    tier: "worker",
    reportsTo: "orch-veronica",
    domain: "Quality & Compliance",
    mission: "Validate outputs, ensure compliance, and reduce operational risk.",
    responsibilities: ["Run QA checklists", "Audit agent outputs", "Report anomalies and risks"],
    outputs: ["QA reports", "Compliance flags", "Risk notes"],
    tools: ["system-status", "runbook"],
    metrics: ["Defect escape rate"],
  },
  {
    id: "worker-data",
    name: "Data Engineer",
    tier: "worker",
    reportsTo: "orch-veronica",
    domain: "Data & Analytics",
    mission: "Maintain data pipelines, analytics, and instrumentation for leadership visibility.",
    responsibilities: [
      "Build and monitor data pipelines",
      "Maintain KPI dashboards",
      "Ensure data quality and lineage",
    ],
    outputs: ["Data pipelines", "Analytics dashboards", "Data quality reports"],
    tools: ["data-lake", "org-kpi-dashboard"],
    metrics: ["Pipeline uptime"],
  },
  {
    id: "worker-automation",
    name: "Workflow Automator",
    tier: "worker",
    reportsTo: "orch-veronica",
    domain: "Automation",
    mission: "Automate repeatable workflows and task execution.",
    responsibilities: ["Build automations", "Monitor task queues", "Optimize throughput"],
    outputs: ["Automation playbooks", "Task run reports", "Automation coverage map"],
    tools: ["workflow-runner", "execution-map"],
    metrics: ["Automation coverage"],
  },
  {
    id: "worker-ux",
    name: "UX Researcher",
    tier: "worker",
    reportsTo: "orch-veronica",
    domain: "UX Research",
    mission: "Capture user insight and usability signals for executive prioritization.",
    responsibilities: ["Run user interviews", "Synthesize feedback", "Report UX risks"],
    outputs: ["UX insight briefs", "Usability findings", "Persona updates"],
    tools: ["user-insights", "content-lab"],
    metrics: ["Insight adoption"],
  },
  {
    id: "worker-ava-sops",
    name: "SOP Librarian",
    tier: "worker",
    reportsTo: "orch-ava",
    domain: "Operations Enablement",
    mission: "Maintain SOP libraries and operational checklists.",
    responsibilities: ["Draft and maintain SOPs", "Version-control procedures", "Ensure SOP adoption"],
    outputs: ["SOP library", "Checklist updates", "Process annotations"],
    tools: ["knowledge-base", "workflow-runner"],
    metrics: ["SOP freshness"],
  },
  {
    id: "worker-ava-routing",
    name: "Task Router",
    tier: "worker",
    reportsTo: "orch-ava",
    domain: "Task Coordination",
    mission: "Route tasks and dependencies across teams.",
    responsibilities: ["Intake new tasks", "Assign owners and dependencies", "Track handoffs"],
    outputs: ["Routing queue", "Dependency map", "Handoff notes"],
    tools: ["execution-map", "workflow-runner"],
    metrics: ["Handoff latency"],
  },
  {
    id: "worker-ava-docs",
    name: "Documentation Steward",
    tier: "worker",
    reportsTo: "orch-ava",
    domain: "Documentation",
    mission: "Keep internal documentation current and discoverable.",
    responsibilities: ["Audit docs for gaps", "Update runbooks", "Align docs to SOPs"],
    outputs: ["Doc updates", "Runbook revisions", "Doc gap list"],
    tools: ["knowledge-base", "workflow-runner"],
    metrics: ["Doc freshness"],
  },
  {
    id: "worker-ava-procurement",
    name: "Vendor Coordinator",
    tier: "worker",
    reportsTo: "orch-ava",
    domain: "Vendor & Admin Ops",
    mission: "Coordinate vendors, licenses, and administrative logistics.",
    responsibilities: ["Track vendor renewals", "Coordinate procurement", "Maintain admin calendars"],
    outputs: ["Vendor tracker", "Renewal alerts", "Admin checklists"],
    tools: ["workflow-runner", "org-kpi-dashboard"],
    metrics: ["Renewal on-time rate"],
  },
  {
    id: "worker-ava-quality",
    name: "Process QA Analyst",
    tier: "worker",
    reportsTo: "orch-ava",
    domain: "Operational Quality",
    mission: "Audit operational workflows for drift and gaps.",
    responsibilities: ["Review process adherence", "Flag bottlenecks", "Recommend fixes"],
    outputs: ["Process QA reports", "Bottleneck list", "Fix recommendations"],
    tools: ["system-status", "execution-map"],
    metrics: ["Process drift rate"],
  },
  {
    id: "worker-finn-recruiting",
    name: "Recruiting Coordinator",
    tier: "worker",
    reportsTo: "orch-finn",
    domain: "Talent Acquisition",
    mission: "Coordinate recruiting workflows and candidate pipelines.",
    responsibilities: ["Source candidate lists", "Schedule interviews", "Maintain pipeline status"],
    outputs: ["Candidate pipeline", "Interview schedules", "Sourcing reports"],
    tools: ["talent-hub", "workflow-runner"],
    metrics: ["Time-to-screen"],
  },
  {
    id: "worker-finn-onboarding",
    name: "Onboarding Specialist",
    tier: "worker",
    reportsTo: "orch-finn",
    domain: "Onboarding",
    mission: "Deliver onboarding playbooks and readiness checks.",
    responsibilities: ["Prepare onboarding packets", "Track training completion", "Run readiness checks"],
    outputs: ["Onboarding checklists", "Training status", "Readiness notes"],
    tools: ["knowledge-base", "workflow-runner"],
    metrics: ["Onboarding completion"],
  },
  {
    id: "worker-finn-policy",
    name: "Policy & Compliance Liaison",
    tier: "worker",
    reportsTo: "orch-finn",
    domain: "HR Compliance",
    mission: "Maintain HR policy updates and compliance checks.",
    responsibilities: ["Draft policy updates", "Track compliance tasks", "Respond to policy questions"],
    outputs: ["Policy change log", "Compliance checklist", "FAQ updates"],
    tools: ["knowledge-base", "system-status"],
    metrics: ["Policy update cycle time"],
  },
  {
    id: "worker-finn-culture",
    name: "Culture & Engagement Lead",
    tier: "worker",
    reportsTo: "orch-finn",
    domain: "Culture",
    mission: "Monitor engagement signals and culture health.",
    responsibilities: ["Run pulse surveys", "Analyze engagement data", "Plan culture rituals"],
    outputs: ["Culture pulse report", "Engagement insights", "Ritual calendar"],
    tools: ["org-kpi-dashboard", "knowledge-base"],
    metrics: ["Engagement score"],
  },
  {
    id: "worker-finn-support",
    name: "Internal Helpdesk",
    tier: "worker",
    reportsTo: "orch-finn",
    domain: "Internal Support",
    mission: "Answer internal questions and resolve HR tickets.",
    responsibilities: ["Respond to internal requests", "Route escalations", "Maintain helpdesk logs"],
    outputs: ["Helpdesk responses", "Escalation notes", "Request analytics"],
    tools: ["knowledge-base", "workflow-runner"],
    metrics: ["Internal response time"],
  },
  {
    id: "worker-cipher-fpna",
    name: "FP&A Analyst",
    tier: "worker",
    reportsTo: "orch-cipher",
    domain: "Financial Planning",
    mission: "Support forecasting, budgeting, and scenario modeling.",
    responsibilities: ["Update forecasts", "Build scenario models", "Track variance drivers"],
    outputs: ["Forecast updates", "Scenario models", "Variance notes"],
    tools: ["finance-ledger", "org-kpi-dashboard"],
    metrics: ["Forecast variance"],
  },
  {
    id: "worker-cipher-billing",
    name: "Revenue & Billing Ops",
    tier: "worker",
    reportsTo: "orch-cipher",
    domain: "Revenue Operations",
    mission: "Maintain billing flows and revenue recognition signals.",
    responsibilities: ["Reconcile invoices", "Track payment status", "Flag revenue risks"],
    outputs: ["Billing tracker", "Revenue notes", "Collections status"],
    tools: ["finance-ledger", "workflow-runner"],
    metrics: ["Days sales outstanding"],
  },
  {
    id: "worker-cipher-cost",
    name: "Cost Optimization Analyst",
    tier: "worker",
    reportsTo: "orch-cipher",
    domain: "Cost Management",
    mission: "Identify and execute cost optimization opportunities.",
    responsibilities: ["Analyze spend", "Recommend savings", "Track savings realization"],
    outputs: ["Spend analysis", "Savings backlog", "Optimization tracker"],
    tools: ["org-kpi-dashboard", "finance-ledger"],
    metrics: ["Savings realized"],
  },
  {
    id: "worker-cipher-dashboard",
    name: "KPI Dashboard Builder",
    tier: "worker",
    reportsTo: "orch-cipher",
    domain: "Analytics Enablement",
    mission: "Build and maintain executive dashboards.",
    responsibilities: ["Design KPI views", "Maintain dashboard data", "Ensure metric definitions"],
    outputs: ["Executive dashboards", "Metric dictionary", "Dashboard change log"],
    tools: ["org-kpi-dashboard", "knowledge-base"],
    metrics: ["Dashboard freshness"],
  },
  {
    id: "worker-cipher-risk",
    name: "Risk & Compliance Analyst",
    tier: "worker",
    reportsTo: "orch-cipher",
    domain: "Financial Risk",
    mission: "Monitor financial risk signals and compliance requirements.",
    responsibilities: ["Track risk indicators", "Review compliance items", "Escalate anomalies"],
    outputs: ["Risk register updates", "Compliance checklist", "Anomaly alerts"],
    tools: ["system-status", "finance-ledger"],
    metrics: ["Risk response time"],
  },
  {
    id: "worker-axel-prospecting",
    name: "Prospecting Researcher",
    tier: "worker",
    reportsTo: "orch-axel",
    domain: "Sales Prospecting",
    mission: "Identify target accounts and decision makers.",
    responsibilities: ["Build account lists", "Research personas", "Verify contact data"],
    outputs: ["Target account list", "Persona notes", "Contact validation"],
    tools: ["crm-insights", "market-intel"],
    metrics: ["Prospect coverage"],
  },
  {
    id: "worker-axel-outbound",
    name: "Outbound Specialist",
    tier: "worker",
    reportsTo: "orch-axel",
    domain: "Outbound Operations",
    mission: "Execute outbound sequences and follow-up workflows.",
    responsibilities: ["Draft outreach sequences", "Monitor response rates", "Coordinate follow-ups"],
    outputs: ["Outbound sequences", "Response summaries", "Follow-up queues"],
    tools: ["crm-insights", "workflow-runner"],
    metrics: ["Reply rate"],
  },
  {
    id: "worker-axel-crm",
    name: "CRM Hygiene Analyst",
    tier: "worker",
    reportsTo: "orch-axel",
    domain: "CRM Operations",
    mission: "Keep CRM data accurate and actionable.",
    responsibilities: ["Deduplicate records", "Standardize fields", "Audit pipeline stages"],
    outputs: ["CRM cleanup log", "Field standards", "Pipeline QA notes"],
    tools: ["crm-insights", "knowledge-base"],
    metrics: ["Data accuracy"],
  },
  {
    id: "worker-axel-proposals",
    name: "Proposal Builder",
    tier: "worker",
    reportsTo: "orch-axel",
    domain: "Sales Enablement",
    mission: "Prepare proposals, quotes, and deal collateral.",
    responsibilities: ["Draft proposal templates", "Customize pricing tables", "Align terms with policy"],
    outputs: ["Proposal drafts", "Pricing tables", "Deal collateral"],
    tools: ["knowledge-base", "workflow-runner"],
    metrics: ["Proposal turnaround time"],
  },
  {
    id: "worker-axel-enablement",
    name: "Sales Enablement",
    tier: "worker",
    reportsTo: "orch-axel",
    domain: "Sales Enablement",
    mission: "Maintain enablement assets and battlecards.",
    responsibilities: ["Update battlecards", "Maintain objection handling", "Track enablement usage"],
    outputs: ["Battlecards", "Enablement library", "Usage insights"],
    tools: ["knowledge-base", "content-lab"],
    metrics: ["Enablement adoption"],
  },
  {
    id: "worker-luna-audience",
    name: "Audience Researcher",
    tier: "worker",
    reportsTo: "orch-luna",
    domain: "Audience Insights",
    mission: "Research target audiences and channel dynamics.",
    responsibilities: ["Analyze audience segments", "Monitor channel signals", "Document insights"],
    outputs: ["Audience profiles", "Channel insights", "Persona updates"],
    tools: ["market-intel", "knowledge-base"],
    metrics: ["Insight adoption"],
  },
  {
    id: "worker-luna-campaign",
    name: "Campaign Manager",
    tier: "worker",
    reportsTo: "orch-luna",
    domain: "Campaign Operations",
    mission: "Launch and monitor marketing campaigns.",
    responsibilities: ["Build campaign plans", "Coordinate assets", "Report performance"],
    outputs: ["Campaign plans", "Launch checklists", "Performance reports"],
    tools: ["content-lab", "workflow-runner"],
    metrics: ["Campaign velocity"],
  },
  {
    id: "worker-luna-content",
    name: "Content Producer",
    tier: "worker",
    reportsTo: "orch-luna",
    domain: "Content Production",
    mission: "Create and ship marketing content assets.",
    responsibilities: ["Draft content", "Coordinate reviews", "Publish assets"],
    outputs: ["Content drafts", "Editorial calendar", "Published assets"],
    tools: ["content-lab", "knowledge-base"],
    metrics: ["Content throughput"],
  },
  {
    id: "worker-luna-distribution",
    name: "Distribution Coordinator",
    tier: "worker",
    reportsTo: "orch-luna",
    domain: "Distribution",
    mission: "Distribute content across channels and track reach.",
    responsibilities: ["Schedule distribution", "Track channel reach", "Coordinate partnerships"],
    outputs: ["Distribution schedules", "Channel performance", "Partner notes"],
    tools: ["workflow-runner", "market-intel"],
    metrics: ["Channel growth"],
  },
  {
    id: "worker-luna-analytics",
    name: "Marketing Analyst",
    tier: "worker",
    reportsTo: "orch-luna",
    domain: "Marketing Analytics",
    mission: "Analyze marketing performance and ROI.",
    responsibilities: ["Track funnel metrics", "Report ROI", "Surface anomalies"],
    outputs: ["Marketing dashboards", "ROI reports", "Anomaly alerts"],
    tools: ["org-kpi-dashboard", "knowledge-base"],
    metrics: ["Marketing ROI"],
  },
  {
    id: "worker-ellie-intake",
    name: "Intake & Routing Specialist",
    tier: "worker",
    reportsTo: "orch-ellie",
    domain: "Client Intake",
    mission: "Handle intake workflows and routing for support requests.",
    responsibilities: ["Capture intake details", "Route requests", "Track intake SLAs"],
    outputs: ["Intake logs", "Routing summaries", "SLA tracker"],
    tools: ["support-hub", "workflow-runner"],
    metrics: ["Intake turnaround"],
  },
  {
    id: "worker-ellie-scheduling",
    name: "Scheduling Coordinator",
    tier: "worker",
    reportsTo: "orch-ellie",
    domain: "Scheduling",
    mission: "Coordinate scheduling and follow-up communications.",
    responsibilities: ["Book appointments", "Confirm attendees", "Send reminders"],
    outputs: ["Scheduling calendar", "Confirmation logs", "Reminder cadence"],
    tools: ["workflow-runner", "support-hub"],
    metrics: ["Scheduling accuracy"],
  },
  {
    id: "worker-ellie-knowledge",
    name: "FAQ Knowledge Curator",
    tier: "worker",
    reportsTo: "orch-ellie",
    domain: "Knowledge Management",
    mission: "Maintain FAQs and support knowledge bases.",
    responsibilities: ["Update FAQs", "Tag knowledge articles", "Monitor content gaps"],
    outputs: ["FAQ updates", "Knowledge tags", "Content gap list"],
    tools: ["knowledge-base", "support-hub"],
    metrics: ["Self-serve resolution rate"],
  },
  {
    id: "worker-ellie-voice",
    name: "Voice QA Monitor",
    tier: "worker",
    reportsTo: "orch-ellie",
    domain: "Voice QA",
    mission: "Monitor call handling quality and escalation signals.",
    responsibilities: ["Review call transcripts", "Score call quality", "Flag escalation risks"],
    outputs: ["Call QA scores", "Escalation alerts", "Quality notes"],
    tools: ["support-hub", "system-status"],
    metrics: ["Call quality score"],
  },
  {
    id: "worker-ellie-accounts",
    name: "Client Relations Manager",
    tier: "worker",
    reportsTo: "orch-ellie",
    domain: "Client Relations",
    mission: "Maintain client communication and relationship health.",
    responsibilities: ["Send status updates", "Track account health", "Coordinate escalations"],
    outputs: ["Client updates", "Account health notes", "Escalation plans"],
    tools: ["support-hub", "org-kpi-dashboard"],
    metrics: ["Account health score"],
  },
  {
    id: "worker-vlite-onboarding",
    name: "Client Onboarding Coordinator",
    tier: "worker",
    reportsTo: "orch-veronica-lite",
    domain: "Client Onboarding",
    mission: "Guide clients through deployment and onboarding.",
    responsibilities: ["Run onboarding checklists", "Coordinate provisioning", "Track readiness"],
    outputs: ["Onboarding checklist", "Provisioning notes", "Readiness status"],
    tools: ["workflow-runner", "knowledge-base"],
    metrics: ["Time-to-onboard"],
  },
  {
    id: "worker-vlite-config",
    name: "Template Configurator",
    tier: "worker",
    reportsTo: "orch-veronica-lite",
    domain: "Client Configuration",
    mission: "Configure templates and workflows for client deployments.",
    responsibilities: ["Customize templates", "Validate configurations", "Document changes"],
    outputs: ["Config templates", "Validation checklist", "Change log"],
    tools: ["workflow-runner", "knowledge-base"],
    metrics: ["Config accuracy"],
  },
  {
    id: "worker-vlite-security",
    name: "Tenant Security Liaison",
    tier: "worker",
    reportsTo: "orch-veronica-lite",
    domain: "Tenant Security",
    mission: "Ensure tenant isolation and security requirements.",
    responsibilities: ["Review security requirements", "Validate access controls", "Track compliance"],
    outputs: ["Security checklist", "Access reviews", "Compliance notes"],
    tools: ["system-status", "knowledge-base"],
    metrics: ["Security review completion"],
  },
  {
    id: "worker-vlite-success",
    name: "Client Success Analyst",
    tier: "worker",
    reportsTo: "orch-veronica-lite",
    domain: "Client Success",
    mission: "Monitor client outcomes and usage health.",
    responsibilities: ["Analyze usage trends", "Flag churn risks", "Recommend success actions"],
    outputs: ["Usage insights", "Churn risk list", "Success recommendations"],
    tools: ["org-kpi-dashboard", "support-hub"],
    metrics: ["Client retention"],
  },
  {
    id: "worker-vlite-support",
    name: "Deployment Support",
    tier: "worker",
    reportsTo: "orch-veronica-lite",
    domain: "Deployment Support",
    mission: "Resolve deployment issues and coordinate escalations.",
    responsibilities: ["Triage deployment tickets", "Coordinate fixes", "Document resolutions"],
    outputs: ["Deployment tickets", "Resolution notes", "Escalation updates"],
    tools: ["system-status", "workflow-runner"],
    metrics: ["Deployment resolution time"],
  },
  {
    id: "worker-audit-process",
    name: "Workflow Auditor",
    tier: "worker",
    reportsTo: "orch-audit",
    domain: "Process Audit",
    mission: "Audit workflow performance and adherence.",
    responsibilities: ["Review workflow runs", "Identify bottlenecks", "Document findings"],
    outputs: ["Audit findings", "Bottleneck list", "Process notes"],
    tools: ["system-status", "org-kpi-dashboard"],
    metrics: ["Audit coverage"],
  },
  {
    id: "worker-audit-roi",
    name: "ROI Analyst",
    tier: "worker",
    reportsTo: "orch-audit",
    domain: "ROI Analysis",
    mission: "Quantify ROI opportunities and expected impact.",
    responsibilities: ["Model savings", "Validate assumptions", "Report ROI impacts"],
    outputs: ["ROI models", "Assumption log", "Impact summary"],
    tools: ["org-kpi-dashboard", "knowledge-base"],
    metrics: ["ROI forecast accuracy"],
  },
  {
    id: "worker-audit-compliance",
    name: "Compliance Checker",
    tier: "worker",
    reportsTo: "orch-audit",
    domain: "Compliance Audit",
    mission: "Validate compliance posture and control coverage.",
    responsibilities: ["Check control evidence", "Track compliance gaps", "Escalate violations"],
    outputs: ["Compliance checklist", "Gap analysis", "Violation alerts"],
    tools: ["knowledge-base", "system-status"],
    metrics: ["Compliance coverage"],
  },
  {
    id: "worker-audit-instrumentation",
    name: "Telemetry Reviewer",
    tier: "worker",
    reportsTo: "orch-audit",
    domain: "Observability",
    mission: "Review instrumentation coverage and data integrity.",
    responsibilities: ["Audit telemetry coverage", "Validate data quality", "Recommend instrumentation fixes"],
    outputs: ["Telemetry audit", "Data quality notes", "Instrumentation backlog"],
    tools: ["system-status", "org-kpi-dashboard"],
    metrics: ["Telemetry coverage"],
  },
  {
    id: "worker-audit-remediation",
    name: "Remediation Planner",
    tier: "worker",
    reportsTo: "orch-audit",
    domain: "Remediation",
    mission: "Plan remediation actions for audit findings.",
    responsibilities: ["Prioritize fixes", "Draft remediation plans", "Track remediation status"],
    outputs: ["Remediation plan", "Priority queue", "Status tracker"],
    tools: ["workflow-runner", "knowledge-base"],
    metrics: ["Remediation closure rate"],
  },
  {
    id: "worker-content-case",
    name: "Case Study Writer",
    tier: "worker",
    reportsTo: "orch-content",
    domain: "Case Studies",
    mission: "Turn builds and outcomes into case studies.",
    responsibilities: ["Interview stakeholders", "Draft narratives", "Finalize case studies"],
    outputs: ["Case study drafts", "Interview notes", "Published case studies"],
    tools: ["content-lab", "knowledge-base"],
    metrics: ["Case study cadence"],
  },
  {
    id: "worker-content-playbooks",
    name: "Playbook Editor",
    tier: "worker",
    reportsTo: "orch-content",
    domain: "Operational Playbooks",
    mission: "Transform workflows into repeatable playbooks.",
    responsibilities: ["Document workflows", "Edit playbooks", "Align to SOPs"],
    outputs: ["Playbook library", "Workflow diagrams", "Revision log"],
    tools: ["knowledge-base", "workflow-runner"],
    metrics: ["Playbook adoption"],
  },
  {
    id: "worker-content-metrics",
    name: "Metrics Storyteller",
    tier: "worker",
    reportsTo: "orch-content",
    domain: "Metrics Storytelling",
    mission: "Translate metrics into clear narratives for stakeholders.",
    responsibilities: ["Interpret performance data", "Draft metric narratives", "Align to outcomes"],
    outputs: ["Metrics narratives", "Performance summaries", "Outcome highlights"],
    tools: ["org-kpi-dashboard", "content-lab"],
    metrics: ["Story impact score"],
  },
  {
    id: "worker-content-repurpose",
    name: "Content Repurposer",
    tier: "worker",
    reportsTo: "orch-content",
    domain: "Content Repurposing",
    mission: "Repurpose content across channels and formats.",
    responsibilities: ["Adapt content formats", "Package assets", "Maintain reuse catalog"],
    outputs: ["Repurposed assets", "Reuse catalog", "Packaging notes"],
    tools: ["content-lab", "workflow-runner"],
    metrics: ["Reuse rate"],
  },
  {
    id: "worker-content-distribution",
    name: "Editorial Distribution",
    tier: "worker",
    reportsTo: "orch-content",
    domain: "Editorial Distribution",
    mission: "Coordinate distribution of content assets.",
    responsibilities: ["Schedule releases", "Coordinate channels", "Track distribution reach"],
    outputs: ["Distribution calendar", "Channel reports", "Reach summary"],
    tools: ["workflow-runner", "market-intel"],
    metrics: ["Distribution reach"],
  },
];

const IMPLEMENTED_TOOLS = new Set([
  "system-status",
  "llm-router",
  "knowledge-base",
  "workflow-runner",
  "org-kpi-dashboard",
  "execution-map",
  "market-intel",
]);

function withImplementedTools(agent: AgentDefinition): AgentDefinition {
  return {
    ...agent,
    tools: agent.tools.filter((tool) => IMPLEMENTED_TOOLS.has(tool)),
  };
}

const registryCeo = withImplementedTools(ceoAgent);
const registryOrchestrators = orchestrators.map(withImplementedTools);
const registryWorkers = workers.map(withImplementedTools);

export const agentRegistry = {
  ceo: registryCeo,
  orchestrators: registryOrchestrators,
  workers: registryWorkers,
  all: [registryCeo, ...registryOrchestrators, ...registryWorkers],
};

export function getAgentById(id: string) {
  return agentRegistry.all.find((agent) => agent.id === id) ?? null;
}
