import type { AgentDefinition } from "./types.js";

const ceoAgent: AgentDefinition = {
  id: "ceo",
  name: "CEO Agent",
  tier: "ceo",
  domain: "Executive Leadership",
  mission: "Set company-wide strategy, align orchestrators, and guard the mission, metrics, and culture.",
  responsibilities: [
    "Define the operating cadence and decision framework",
    "Resolve trade-offs across product, growth, and operations",
    "Approve quarterly objectives and resource allocation",
    "Maintain a live view of risk, security, and compliance posture",
  ],
  outputs: [
    "Quarterly objective map",
    "Company operating memo",
    "Executive decision log",
    "Risk posture summary",
  ],
  tools: ["llm-router", "org-kpi-dashboard", "market-intel", "execution-map"],
  metrics: ["Strategic alignment score", "Objective hit rate", "Risk exposure trend"],
};

const orchestrators: AgentDefinition[] = [
  {
    id: "orch-strategy",
    name: "Strategy Orchestrator",
    tier: "orchestrator",
    domain: "Strategy & Market Intelligence",
    mission: "Translate signals into actionable strategic options and competitive positioning.",
    responsibilities: [
      "Monitor market shifts and competitor moves",
      "Run scenario planning and growth modeling",
      "Maintain the strategic narrative for go-to-market",
    ],
    outputs: ["Strategy briefs", "Scenario matrices", "Market signal summaries"],
    tools: ["market-intel", "llm-router"],
    metrics: ["Signal-to-decision latency", "Strategy adoption rate"],
  },
  {
    id: "orch-product",
    name: "Product Orchestrator",
    tier: "orchestrator",
    domain: "Product & UX",
    mission: "Shape product direction, customer value, and roadmap prioritization.",
    responsibilities: [
      "Own the product roadmap and discovery pipeline",
      "Align UX research with delivery",
      "Define success criteria for releases",
    ],
    outputs: ["Roadmap", "Opportunity backlog", "Release scorecards"],
    tools: ["user-insights", "llm-router", "execution-map"],
    metrics: ["Roadmap accuracy", "Feature adoption"],
  },
  {
    id: "orch-engineering",
    name: "Engineering Orchestrator",
    tier: "orchestrator",
    domain: "Engineering & Platform",
    mission: "Deliver resilient infrastructure, runtime safety, and developer velocity.",
    responsibilities: [
      "Coordinate platform reliability and scalability",
      "Set engineering guardrails and standards",
      "Supervise deployment, observability, and incident response",
    ],
    outputs: ["Architecture decisions", "Reliability reports", "Engineering standards"],
    tools: ["system-status", "runbook", "llm-router"],
    metrics: ["Deployment frequency", "Incident MTTR"],
  },
  {
    id: "orch-operations",
    name: "Operations Orchestrator",
    tier: "orchestrator",
    domain: "Operations & Delivery",
    mission: "Keep execution on track across teams, vendors, and deliverables.",
    responsibilities: [
      "Own the operating cadence and sprint health",
      "Coordinate cross-team dependencies",
      "Maintain the delivery risk register",
    ],
    outputs: ["Operating cadence", "Dependency map", "Risk register"],
    tools: ["execution-map", "org-kpi-dashboard", "llm-router"],
    metrics: ["Cycle time", "Delivery predictability"],
  },
  {
    id: "orch-growth",
    name: "Growth Orchestrator",
    tier: "orchestrator",
    domain: "Growth & Marketing",
    mission: "Design repeatable demand systems and market messaging.",
    responsibilities: [
      "Own acquisition and activation loops",
      "Coordinate campaigns and content systems",
      "Measure funnel efficiency",
    ],
    outputs: ["Growth experiments", "Campaign briefs", "Funnel metrics"],
    tools: ["market-intel", "content-lab", "llm-router"],
    metrics: ["CAC efficiency", "Activation rate"],
  },
  {
    id: "orch-sales",
    name: "Sales Orchestrator",
    tier: "orchestrator",
    domain: "Sales & Partnerships",
    mission: "Scale revenue pipeline, partnerships, and enterprise readiness.",
    responsibilities: [
      "Manage pipeline health and forecasting",
      "Coordinate partnership strategy",
      "Ensure enterprise enablement content",
    ],
    outputs: ["Pipeline snapshot", "Partnership plan", "Deal enablement kit"],
    tools: ["crm-insights", "llm-router"],
    metrics: ["Pipeline coverage", "Win rate"],
  },
  {
    id: "orch-customer",
    name: "Customer Orchestrator",
    tier: "orchestrator",
    domain: "Customer Success & Support",
    mission: "Protect retention, satisfaction, and trusted outcomes for customers.",
    responsibilities: [
      "Monitor customer health and churn risk",
      "Coordinate support escalation playbooks",
      "Own success metrics and onboarding",
    ],
    outputs: ["Health scores", "Retention playbooks", "Onboarding plans"],
    tools: ["support-hub", "llm-router"],
    metrics: ["Net retention", "Time-to-value"],
  },
  {
    id: "orch-finance",
    name: "Finance Orchestrator",
    tier: "orchestrator",
    domain: "Finance & Risk",
    mission: "Keep financial health, risk exposure, and runway transparent.",
    responsibilities: [
      "Forecast cash flow and runway",
      "Monitor budget and ROI",
      "Report risk exposure and compliance items",
    ],
    outputs: ["Runway model", "Budget variance", "Risk summary"],
    tools: ["finance-ledger", "llm-router"],
    metrics: ["Burn multiple", "Forecast accuracy"],
  },
  {
    id: "orch-people",
    name: "People Orchestrator",
    tier: "orchestrator",
    domain: "People & Culture",
    mission: "Scale talent, performance, and culture across human + AI workforce.",
    responsibilities: [
      "Track capacity and hiring pipeline",
      "Coordinate performance reviews",
      "Maintain culture and learning cadence",
    ],
    outputs: ["Capacity plan", "Performance insights", "Culture pulse"],
    tools: ["talent-hub", "llm-router"],
    metrics: ["Capacity utilization", "Team health"],
  },
];

const workers: AgentDefinition[] = [
  {
    id: "worker-research",
    name: "Research Analyst",
    tier: "worker",
    domain: "Research & Intelligence",
    mission: "Collect and synthesize high-signal research for orchestrators.",
    responsibilities: ["Run deep research", "Summarize findings", "Maintain citations"],
    outputs: ["Research briefs", "Competitive snapshots"],
    tools: ["market-intel", "knowledge-base"],
    metrics: ["Insight hit rate"],
  },
  {
    id: "worker-qa",
    name: "QA Auditor",
    tier: "worker",
    domain: "Quality & Compliance",
    mission: "Validate outputs, ensure compliance, and reduce operational risk.",
    responsibilities: ["Run QA checklists", "Audit outputs", "Report anomalies"],
    outputs: ["QA reports", "Compliance flags"],
    tools: ["runbook", "system-status"],
    metrics: ["Defect escape rate"],
  },
  {
    id: "worker-data",
    name: "Data Engineer",
    tier: "worker",
    domain: "Data & Analytics",
    mission: "Maintain data pipelines, analytics, and instrumentation.",
    responsibilities: ["Build data pipelines", "Maintain metrics", "Optimize storage"],
    outputs: ["Data pipelines", "Analytics dashboards"],
    tools: ["data-lake", "org-kpi-dashboard"],
    metrics: ["Pipeline uptime"],
  },
  {
    id: "worker-automation",
    name: "Workflow Automator",
    tier: "worker",
    domain: "Automation",
    mission: "Automate repeatable workflows and task execution.",
    responsibilities: ["Build automations", "Monitor task queues", "Optimize throughput"],
    outputs: ["Automation playbooks", "Task run reports"],
    tools: ["workflow-runner", "execution-map"],
    metrics: ["Automation coverage"],
  },
  {
    id: "worker-ux",
    name: "UX Researcher",
    tier: "worker",
    domain: "UX Research",
    mission: "Capture customer insight and usability signals.",
    responsibilities: ["Run user interviews", "Synthesize feedback", "Report UX risks"],
    outputs: ["UX insight briefs", "Usability findings"],
    tools: ["user-insights", "content-lab"],
    metrics: ["Insight adoption"],
  },
];

export const agentRegistry = {
  ceo: ceoAgent,
  orchestrators,
  workers,
  all: [ceoAgent, ...orchestrators, ...workers],
};

export function getAgentById(id: string) {
  return agentRegistry.all.find((agent) => agent.id === id) ?? null;
}
