/**
 * Contract Types — GENERATED by scripts/sync-contracts.ts
 * DO NOT EDIT. Edit contracts/schema.json and re-run.
 */
export const CONTRACT_VERSION = "1.1.0" as const;

// Drift-check hash (mirrored in Python): a7e92f6b
export const CONTRACT_DEFINITIONS: ReadonlyArray<string> = ["LlmProvider","AgentEventType","AgentRunRequest","AgentEvent","AgentRunResult","LlmRequest","LlmResponse","LlmUsage"];

export type LlmProvider = "openai" | "anthropic";

export type AgentEventType = "tool_call" | "tool_result" | "message" | "error" | "approval_requested" | "approval_granted" | "approval_denied";

export interface AgentRunRequest {
  agentId: string;
  input: Record<string, unknown>;
  context?: Record<string, unknown>;
  orgId?: string;
  threadId?: unknown;
}

export interface AgentEvent {
  type: AgentEventType;
  timestamp: string;
  payload: Record<string, unknown>;
}

export interface AgentRunResult {
  success: boolean;
  output: Record<string, unknown>;
  events: Array<AgentEvent>;
  error?: unknown;
  approvalId?: unknown;
}

export interface LlmRequest {
  provider: LlmProvider;
  model: string;
  input: string;
  system?: string;
  temperature?: number;
  maxTokens?: number;
}

export interface LlmResponse {
  provider: LlmProvider;
  model: string;
  text: string;
  usage?: LlmUsage;
}

export interface LlmUsage {
  inputTokens?: number;
  outputTokens?: number;
}
