import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import App from "./App";
import { AgentsPage } from "./pages/agents";
import { ConsolePage } from "./pages/console";
import { RunsPage } from "./pages/runs";
import "./index.css";
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(App, {}) }), _jsx(Route, { path: "/agents", element: _jsx(AgentsPage, {}) }), _jsx(Route, { path: "/console/:agentId", element: _jsx(ConsolePage, {}) }), _jsx(Route, { path: "/runs", element: _jsx(RunsPage, {}) })] }) }) }));
